name: Deploy stage
on:
  push:
    branches:
      - "homologacao"

jobs:
  deploy:
    name: Deploy stage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy Files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          local-dir: "./"
          server-dir: "./apihom.cache.flexconsulta/"
          git-ftp-args: "--changed-only"
      - name: Install Dependencies
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /var/www/group-apis/apihom.cache.flexconsulta
            yarn
            yarn prisma generate --schema ./prisma/schema1.prisma
